name: Hello world Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World"
        shell: bash

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'ItsDaveTheWave'
          git config --global user.email 'itsdavidch@gmail.com'
          git add report.txt
          git commit -m "Automated report"
          git push
